# -*- coding: utf-8 -*-
"""resume.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fe23mzQ-glGDbRwcAuZq_q6-cbdsieeN
"""

def recommend_projects(interest):
    all_projects = {
        "machine learning": ["Spam Detection", "Resume Analyzer", "Stock Price Predictor"],
        "web development": ["Portfolio Website", "Blog Platform", "E-commerce Clone"],
        "ai": ["AI Chatbot", "Smart Virtual Assistant"]
    }
    return all_projects.get(interest.lower(), ["No matching projects found."])

def get_hr_response(question):
    responses = {
        "tell me about yourself": "I am a final year engineering student with a passion for AI and Python development.",
        "what are your strengths": "My strengths include problem solving, quick learning, and adaptability.",
        "why should we hire you": "Because I bring hands-on project experience and a deep interest in machine learning."
    }
    return responses.get(question.lower(), "Sorry, I don't have an answer for that yet.")

def analyze_resume(text):
    skills = ["Python", "Machine Learning", "Data Analysis", "Flask", "Pandas"]
    missing = [skill for skill in skills if skill.lower() not in text.lower()]
    score = max(0, 10 - len(missing) * 2)
    return {
        "score": score,
        "missing_skills": missing,
        "summary": "Resume analysis complete."
    }

def main():
    print("Welcome to the ML-Powered Portfolio Assistant (Python Version)")
    while True:
        print("\nChoose an option:")
        print("1. Analyze Resume")
        print("2. Recommend Projects")
        print("3. HR Interview Bot")
        print("4. Exit")
        choice = input("Enter your choice (1-4): ")

        if choice == '1':
            text = input("Paste your resume text here:\n")
            result = analyze_resume(text)
            print(f"\nResume Score: {result['score']}/10")
            print("Missing Skills:", ", ".join(result['missing_skills']))
            print(result['summary'])

        elif choice == '2':
            interest = input("Enter your interest (e.g., Machine Learning, Web Development, AI): ")
            projects = recommend_projects(interest)
            print("\nRecommended Projects:")
            for p in projects:
                print("-", p)

        elif choice == '3':
            question = input("Ask an HR interview question: ")
            answer = get_hr_response(question)
            print("Bot:", answer)

        elif choice == '4':
            print("Goodbye!")
            break
        else:
            print("Invalid choice. Please try again.")

if __name__ == "__main__":
    main()